# Homebrew Formula for Mumei — auto-generated by release workflow
class Mumei < Formula
  desc "Mathematical Proof-Driven Programming Language — formally verified with Z3"
  homepage "https://github.com/mumei-lang/mumei"
  license "MIT"
  version "0.2.11"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/mumei-lang/mumei/releases/download/v0.2.11/mumei-aarch64-apple-darwin.tar.gz"
      sha256 "9f5f3edd7985f600eefee90360931409984bb5e50d58e00f9bc6eeba62986cdb"
    else
      url "https://github.com/mumei-lang/mumei/releases/download/v0.2.11/mumei-x86_64-apple-darwin.tar.gz"
      sha256 "0b81adc4f0fb18990dd40cd8da96fa98de92abd0d4da3e65fa686fae85de7dff"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/mumei-lang/mumei/releases/download/v0.2.11/mumei-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "044282a6dc10f666eda4f86db2d02d618dba3e017122d481daf7b0795bf3dbef"
    else
      url "https://github.com/mumei-lang/mumei/releases/download/v0.2.11/mumei-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "ea6b657f31e53dec288c0ba6fc954c75cca034776ca6ae5bf573551edddce9cf"
    end
  end

  depends_on "z3"
  depends_on "llvm@17"

  def install
    bin.install "mumei"
    (share/"mumei/std").install Dir["std/*"]

    env_script = <<~EOS
      export MUMEI_STD_PATH="#{share}/mumei/std"
    EOS
    (etc/"mumei").mkpath
    (etc/"mumei/env.sh").write env_script
  end

  def caveats
    <<~EOS
      The Mumei standard library has been installed to:
        #{share}/mumei/std

      To use it, add the following to your shell profile:
        export MUMEI_STD_PATH="#{share}/mumei/std"

      Or source the environment file:
        source #{etc}/mumei/env.sh
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/mumei --version")
  end
end
