# Homebrew Formula for Mumei — auto-generated by release workflow
class Mumei < Formula
  desc "Mathematical Proof-Driven Programming Language — formally verified with Z3"
  homepage "https://github.com/mumei-lang/mumei"
  license "MIT"
  version "0.4.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/mumei-lang/mumei/releases/download/v0.4.1/mumei-aarch64-apple-darwin.tar.gz"
      sha256 "2896277da115f40351521537e3b7dc4c3eb1d7e9b37ba456743caae5258a7430"
    else
      url "https://github.com/mumei-lang/mumei/releases/download/v0.4.1/mumei-x86_64-apple-darwin.tar.gz"
      sha256 "a1969ca21590959bb4f18b00a5fa3f5b51da27fe58003403b988b901eb04a4d0"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/mumei-lang/mumei/releases/download/v0.4.1/mumei-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "f6911b68d43dba3ec50a982a081bfb78c652491de0b6bf0a151bfd5fa7f17f37"
    else
      url "https://github.com/mumei-lang/mumei/releases/download/v0.4.1/mumei-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "a5e35eefede77578909880ed6024685f5265b4e103886b65a316e694d8dded98"
    end
  end

  depends_on "z3"
  depends_on "llvm@17"

  def install
    bin.install "mumei"
    (share/"mumei/std").install Dir["std/*"]

    env_script = <<~EOS
      export MUMEI_STD_PATH="#{share}/mumei/std"
    EOS
    (etc/"mumei").mkpath
    (etc/"mumei/env.sh").write env_script
  end

  def caveats
    <<~EOS
      The Mumei standard library has been installed to:
        #{share}/mumei/std

      To use it, add the following to your shell profile:
        export MUMEI_STD_PATH="#{share}/mumei/std"

      Or source the environment file:
        source #{etc}/mumei/env.sh
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/mumei --version")
  end
end
