# Homebrew Formula for Mumei — auto-generated by release workflow
class Mumei < Formula
  desc "Mathematical Proof-Driven Programming Language — formally verified with Z3"
  homepage "https://github.com/mumei-lang/mumei"
  license "MIT"
  version "0.5.6"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/mumei-lang/mumei/releases/download/v0.5.6/mumei-aarch64-apple-darwin.tar.gz"
      sha256 "dc99b69f4dfb1f013ab59af734f5777dc251effb6c430215ab54d320ac1050f4"
    else
      url "https://github.com/mumei-lang/mumei/releases/download/v0.5.6/mumei-x86_64-apple-darwin.tar.gz"
      sha256 "e41c60a77eb47f139eccfc5d7a4a5ba6395900c8fc8ebd2a54627fa8b5d71597"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/mumei-lang/mumei/releases/download/v0.5.6/mumei-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "238cdbb65343ff49d101e111015ea5c2d952401e0e66e96366f7ca0e5fcffdca"
    else
      url "https://github.com/mumei-lang/mumei/releases/download/v0.5.6/mumei-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "239859872cea3d546b4e9c4c267ebabd8b2f51ea44a641812268f31d268cf6a2"
    end
  end

  depends_on "z3"
  depends_on "llvm@17"

  def install
    bin.install "mumei"
    (share/"mumei/std").install Dir["std/*"]

    # SI-5 Phase 3-C: install the std/ proof-certificate bundle when it
    # ships with the release tarball so downstream projects can verify
    # imports against a trusted, versioned certificate set.
    has_proof_bundle = File.exist?("std-proof-bundle.json")
    if has_proof_bundle
      (share/"mumei").install "std-proof-bundle.json"
    end

    env_script = "export MUMEI_STD_PATH=\"#{share}/mumei/std\"\n"
    if has_proof_bundle
      env_script += "export MUMEI_PROOF_BUNDLE=\"#{share}/mumei/std-proof-bundle.json\"\n"
    end
    (etc/"mumei").mkpath
    (etc/"mumei/env.sh").write env_script
  end

  def caveats
    s = <<~EOS
      The Mumei standard library has been installed to:
        #{share}/mumei/std

    EOS
    if (share/"mumei/std-proof-bundle.json").exist?
      s += <<~EOS
        The std/ proof-certificate bundle (SI-5 Phase 3-C) is at:
          #{share}/mumei/std-proof-bundle.json

      EOS
    end
    s += <<~EOS
      To use it, add the following to your shell profile:
        export MUMEI_STD_PATH="#{share}/mumei/std"
    EOS
    if (share/"mumei/std-proof-bundle.json").exist?
      s += "  export MUMEI_PROOF_BUNDLE=\"#{share}/mumei/std-proof-bundle.json\"\n"
    end
    s += <<~EOS

      Or source the environment file:
        source #{etc}/mumei/env.sh
    EOS
    s
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/mumei --version")
  end
end
